### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by Prestadev2020** [wfpaisa/prestashop-custom-field#1]
Thank you for module, when I try to install module rom admin module and search, its not showing
after that I did created zip and upload from admin module, I got internal error, I alrady created field in customer table

**Comment by jibbewillem** [comment]
I too can't find the module in de list of modules.

**Comment by Prestadev2020** [comment]
> I too can't find the module in de list of modules.

I found and its working

**Comment by jibbewillem** [comment]
Can you explain the steps for me? Thanks

**Comment by Prestadev2020** [comment]
can you tell me what you need? I installed module from admin Module

**Comment by wfpaisa** [comment]
go to Module catalog and search for the module "prestashop-custom-field"

**Comment by jibbewillem** [comment]
Thanks! I found it by searching "custom field" and scrolling down a bit.
